wip

diff --git a/.github/workflows/docker-compose-test.yml b/.github/workflows/docker-compose-test.yml
--- a/.github/workflows/docker-compose-test.yml
+++ b/.github/workflows/docker-compose-test.yml
@@ -21,27 +21,27 @@ jobs:
       - name: Start Hadoop Ecosystem
         run: docker compose up -d
 
-      - name: Wait for core services to be healthy
-        timeout-minutes: 10 # Give enough time for services to start
-        run: |
-          services=("namenode" "zookeeper" "hive-metastore-db" "kafka" "hive-metastore" "hiveserver2" "spark-master" "flink-jobmanager" "trino-coordinator")
-          for service in "${services[@]}"; do
-            echo "Waiting for $service to be healthy..."
-            for i in $(seq 1 60); do # Check for up to 600 seconds (10 minutes)
-              status=$(docker compose ps -a $service | grep $service | awk '{print $NF}')
-              if [[ "$status" == "(healthy)" || "$status" == "Up" ]]; then
-                echo "$service is healthy/up."
-                break
-              fi
-              if [ $i -eq 60 ]; then
-                echo "Error: $service did not become healthy/up within the timeout."
-                docker compose logs $service
-                exit 1
-              fi
-              sleep 10 # Check every 10 seconds
-            done
-          done
-          echo "All core services are healthy/up."
+      # - name: Wait for core services to be healthy
+      #   timeout-minutes: 10 # Give enough time for services to start
+      #   run: |
+      #     services=("namenode" "zookeeper" "hive-metastore-db" "kafka" "hive-metastore" "hiveserver2" "spark-master" "flink-jobmanager" "trino-coordinator")
+      #     for service in "${services[@]}"; do
+      #       echo "Waiting for $service to be healthy..."
+      #       for i in $(seq 1 60); do # Check for up to 600 seconds (10 minutes)
+      #         status=$(docker compose ps -a $service | grep $service | awk '{print $NF}')
+      #         if [[ "$status" == "(healthy)" || "$status" == "Up" ]]; then
+      #           echo "$service is healthy/up."
+      #           break
+      #         fi
+      #         if [ $i -eq 60 ]; then
+      #           echo "Error: $service did not become healthy/up within the timeout."
+      #           docker compose logs $service
+      #           exit 1
+      #         fi
+      #         sleep 10 # Check every 10 seconds
+      #       done
+      #     done
+      #     echo "All core services are healthy/up."
 
       - name: Test HDFS functionality
         run: docker exec namenode hdfs dfs -mkdir -p /test_dir && docker exec namenode hdfs dfs -ls /
